version: '2.4'
services:
  server:
    container_name: php-apache
    build: 
      context: ./php/
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./php/src/:/var/www/html/
    ports:
      - "8000:80"
  
  frontend: 
    container_name: react 
    build: 
      context: ./app/
      dockerfile: Dockerfile
    depends_on:
      # - php-apache
      - server
    ports: 
      - "3000:3000"
    stdin_open: true
    volumes: 
      - /app/
      - /app/node_modules/    

  db: 
    container_name: db
    image: mysql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: MYSQL_DATABASE
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    healthcheck: 
      test: ["CMD", "mysqladmin","ping","-h","localhost"]
      timeout: 20s
      retries: 10
    ports: 
      - "3306:3306"
    cap_add: [ SYS_NICE ]
    volumes: 
      - ./data/:/var/lib/mysql/
  
  phpmyadmin: 
    restart: always
    image: phpmyadmin/phpmyadmin
    ports: 
      - "8080:80"
    environment: 
      PMA_PORT: 3306
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: password
    depends_on:
      db:
        condition: service_healthy
  
  
